"""empty message

Revision ID: 68c9aca9e670
Revises: 
Create Date: 2020-02-19 16:56:36.060937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c9aca9e670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=180), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('account_num', sa.String(length=120), nullable=False),
    sa.Column('account_amount', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_amount'),
    sa.UniqueConstraint('account_num'),
    sa.UniqueConstraint('fullname'),
    sa.UniqueConstraint('password')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=180), nullable=True),
    sa.Column('time', sa.String(length=180), nullable=True),
    sa.Column('amount', sa.String(length=180), nullable=True),
    sa.Column('item', sa.String(length=180), nullable=True),
    sa.Column('state', sa.String(length=180), nullable=True),
    sa.Column('city', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('person')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
